image: "rust:latest"

before_script:
  - apt-get update -qq && apt-get install -qqy xorg-dev libxcb-util0-dev libxcb-keysyms1-dev

build:
  stage: build
  script:
    - cargo check
    - cargo build
    - cargo test
